spring:
  application:
    name: Comment-service
  datasource:
    username: root
    url: jdbc:mysql://localhost:9090/cs544
    password: root
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #eureka port
