spring:
  application:
    name: Blogging-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:9090/blogDB
    password: root
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  main:
    banner-mode: off
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #eureka port

